### ISSUE TITLE
使用 Vite + React 開發登入頁面

### ISSUE THREAD

**Issue by s35241607** [s35241607/lan-side-project#7]
### 描述  
為應用程式開發一個登入頁面，使用 **Vite** 和 **React**。頁面需包含以下內容：  
- **使用者名稱**與**密碼**輸入欄位。  
- **登入**按鈕。  
- 適當的**表單驗證**（例如：必填欄位、密碼長度等）。  
- **錯誤訊息**提示（針對登入失敗）。  
- 與後端 API 的整合以進行使用者驗證。  

設計需符合 UI/UX 指南，若需要可使用 Tailwind 進行樣式設計。  

### 驗收標準  
1. 功能正常且外觀美觀的登入頁面。  
2. 所有驗證功能正確實現並與後端 API 正確連接。

**Comment by s35241607** [comment]
@ChiuZhenHuang 改用 react 開發，直接在 frontend 資料夾新增一個 react 就好

**Comment by ChiuZhenHuang** [comment]
ok 已新增

**Comment by s35241607** [comment]
@ChiuZhenHuang 要多久？

**Comment by ChiuZhenHuang** [comment]
給我一首歌的時間
